GET localhost:3000/rooms

###
POST http://localhost:3000/rooms
Content-Type: application/json

{
  "imagen": "10987",
  "nombre": "Sala 5",
  "descripcion": "Sala de testeo de insert de datos 4",
  "restricciones": "No se permiten niños",
  "estado": true
}

###
DELETE http://localhost:3000/rooms/1

###
PATCH http://localhost:3000/rooms/2
Content-Type: application/json

{
  "nombre": "Brandon"
}