
### "GetAll"
GET localhost:3000/states
### "GetById"
GET localhost:3000/states/2

### "Post"
POST http://localhost:3000/states
Content-Type: application/json

{
  "tipo": "Disponible"
}

### "Delete"
DELETE http://localhost:3000/states/1

### "Patch"
PATCH http://localhost:3000/states/2
Content-Type: application/json

{
  "tipo": "Prestado"
}