###
GET http://localhost:3000/assets

###
POST http://localhost:3000/assets
Content-Type: application/json

{
  "numeroPlaca": 182732645,
  "nombre": "Luz",
  "descripcion": "LUZ luminosa",
  "modelo": "HP Pavilion",
  "numeroSerie": "18273bbb4234",
  "marca": "HP",
  "idEstado": 1,
  "condicion": true,
  "idCategoria": 2
}

###
GET http://localhost:3000/assets/category/2

###
GET http://localhost:3000/assets/182732645

###
DELETE http://localhost:3000/assets/182732645

###
PATCH http://localhost:3000/assets/182732645
Content-Type: application/json

{
  "numeroSerie": "18273bbb"
}