GET localhost:3000/rooms

###
POST http://localhost:3000/rooms
Content-Type: application/json

{
  "imagen": "10987",
  "nombre": "Sala sigi",
  "descripcion": "Sala de testeo de insert de datos 4",
  "restricciones": "No se permiten niños",
  "estado": true
}

###
DELETE http://localhost:3000/rooms/3

###
PATCH http://localhost:3000/rooms/5
Content-Type: application/json

{
  "nombre": "Sala brandon"
}

###Estos son los endpoints de la tabla roles
###
GET http://localhost:3000/roles

###
POST http://localhost:3000/roles
Content-Type: application/json

{
  "nombre": "Administrador"
}

###
DELETE http://localhost:3000/roles/1

###
PATCH http://localhost:3000/roles/2
Content-Type: application/json

{
  "nombre": "Estudiante"
}

###Estos son los endpoints de la tabla categories
###
GET http://localhost:3000/categories


###
POST http://localhost:3000/categories
Content-Type: application/json

{
  "nombre": "Laptop"
}

###
DELETE http://localhost:3000/categories/1

###
PATCH http://localhost:3000/categories/2
Content-Type: application/json

{
  "nombre": "Laptop"
}